spring.application.name=chatbot-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/chatbot_db
spring.datasource.username=postgres
spring.datasource.password=123456

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.bot=DEBUG

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# TODO: Điền tài khoản email và App Password
spring.mail.username=datpham100705@gmail.com
spring.mail.password=gkcrpmnokqlrkrty
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
