"""
Script tạo dữ liệu Out-of-Scope + bổ sung intent giao tiếp
Chạy: python generate_oos_data.py
Output: Append vào data/intent_dataset.csv
"""

import csv
import os
import collections

# Path to dataset
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATASET_PATH = os.path.join(SCRIPT_DIR, "data", "intent_dataset.csv")

# ==============================================================================
# 1. DỮ LIỆU OUT_OF_SCOPE (~800 câu, 9 nhóm chủ đề)
# ==============================================================================

oos_chinh_tri = [
    "Ai là chủ tịch nước Việt Nam",
    "Ai là tổng thống Mỹ",
    "Bầu cử tổng thống khi nào",
    "Chính sách ngoại giao Việt Nam",
    "Chiến tranh Ukraine khi nào kết thúc",
    "Đảng cộng sản Việt Nam thành lập năm nào",
    "Quốc hội họp khi nào",
    "Chủ nghĩa xã hội là gì",
    "Quan hệ Việt Mỹ như thế nào",
    "Hiến pháp Việt Nam ban hành năm nào",
    "Thủ tướng Việt Nam là ai",
    "Bộ trưởng bộ giáo dục là ai",
    "Chính phủ có bao nhiêu bộ",
    "Quốc hội có bao nhiêu đại biểu",
    "Luật lao động quy định gì",
    "Tình hình biển Đông như thế nào",
    "Trung Quốc có bao nhiêu dân",
    "Liên Hợp Quốc là gì",
    "NATO là tổ chức gì",
    "ASEAN gồm những nước nào",
    "Tổng bí thư là ai",
    "Đại hội đảng khi nào",
    "Hội đồng nhân dân là gì",
    "Cải cách hành chính là gì",
    "Phong trào dân chủ là gì",
    "Nhân quyền là gì",
    "Quyền tự do ngôn luận",
    "Xung đột Israel Palestine",
    "Tổng thống Pháp là ai",
    "Thủ tướng Nhật Bản là ai",
    "Cách mạng tháng 8 năm nào",
    "Chiến dịch Điện Biên Phủ",
    "Hiệp định Geneva ký năm nào",
    "Đổi mới kinh tế năm nào",
    "Gia nhập WTO năm nào",
    "Chủ tịch Hồ Chí Minh sinh năm nào",
    "Quốc khánh Việt Nam ngày nào",
    "Đại hội đảng lần thứ mấy",
    "Hiến pháp có bao nhiêu chương",
    "Luật đất đai mới có gì",
    "Bộ luật hình sự quy định gì",
    "An ninh quốc phòng như thế nào",
    "Chính sách đối ngoại của Mỹ",
    "Brexit là gì",
    "Liên minh châu Âu gồm mấy nước",
    "Hội nghị thượng đỉnh G7",
    "Biến đổi khí hậu chính sách",
    "Bầu cử giữa kỳ Mỹ",
    "Tổng thống Nga là ai",
    "Chiến tranh lạnh là gì",
    "Cách mạng công nghiệp lần thứ 4",
    "Chính trị Thái Lan như nào",
    "Đảo chính Myanmar",
    "Bộ máy nhà nước Việt Nam",
    "Chế độ chính trị là gì",
    "Phát triển bền vững là gì",
    "Mục tiêu thiên niên kỷ",
    "Quyền con người nghĩa là gì",
    "Tự do báo chí ở Việt Nam",
    "Kinh tế thị trường là gì",
    "Kinh tế kế hoạch tập trung",
    "Cổ phần hóa doanh nghiệp nhà nước",
    "Tham nhũng ở Việt Nam",
    "Phòng chống tham nhũng",
    "Luật phòng chống ma túy",
    "Tội phạm mạng xử lý thế nào",
    "An ninh mạng Việt Nam",
    "Luật an ninh mạng là gì",
    "Kiểm duyệt internet",
    "Tự do internet ở Việt Nam",
    "Chủ quyền biển đảo",
    "Hoàng Sa Trường Sa thuộc nước nào",
    "Đường lưỡi bò là gì",
    "Công ước luật biển UNCLOS",
    "Quan hệ Việt Trung",
    "Quan hệ Việt Nhật",
    "FTA Việt Nam ký với nước nào",
    "CPTPP là hiệp định gì",
    "RCEP có lợi gì cho Việt Nam",
    "Chính sách thuế mới",
    "Luật thuế thu nhập cá nhân",
    "Cải cách giáo dục",
    "Đổi mới chương trình giáo dục",
    "Xóa đói giảm nghèo",
    "Bảo hiểm xã hội là gì",
    "Lương tối thiểu vùng bao nhiêu",
    "Tuổi nghỉ hưu mới là bao nhiêu",
    "Luật lao động mới có gì thay đổi",
    "Chính sách hỗ trợ doanh nghiệp",
    "Startup Việt Nam được hỗ trợ gì",
    "Đầu tư công trung hạn",
    "ODA là gì",
    "Viện trợ quốc tế cho Việt Nam",
    "GDP Việt Nam bao nhiêu",
    "Lạm phát năm nay bao nhiêu phần trăm",
    "Tỷ giá USD hôm nay",
    "Ngân hàng nhà nước tăng lãi suất",
    "Chính sách tiền tệ nới lỏng",
    "Thị trường bất động sản Việt Nam",
]

oos_khoa_hoc_toan = [
    "Giải phương trình x^2 = 4",
    "Công thức tính diện tích hình tròn",
    "Trái đất nặng bao nhiêu",
    "Tốc độ ánh sáng là bao nhiêu",
    "Nguyên tử hydro có mấy electron",
    "Công thức hóa học của nước",
    "Định lý Pythagoras là gì",
    "Số pi bằng bao nhiêu",
    "Einstein phát minh ra gì",
    "Hố đen vũ trụ là gì",
    "Mặt trời cách trái đất bao xa",
    "Hệ mặt trời có mấy hành tinh",
    "Sao Hỏa có sự sống không",
    "DNA là gì",
    "Tế bào là gì",
    "Quang hợp là quá trình gì",
    "Vi khuẩn và virus khác nhau thế nào",
    "Thuyết tương đối là gì",
    "Lực hấp dẫn là gì",
    "Tính tích phân hàm sin",
    "Ma trận nghịch đảo tính thế nào",
    "Logarit tự nhiên là gì",
    "Giải hệ phương trình 2 ẩn",
    "Tính đạo hàm của x^3",
    "Dãy Fibonacci là gì",
    "Số nguyên tố là gì",
    "Tam giác đều có tính chất gì",
    "Vector là gì",
    "Xác suất tung đồng xu",
    "Thống kê mô tả là gì",
    "Phương sai và độ lệch chuẩn",
    "Hàm số bậc 2 đồ thị thế nào",
    "Sin cos tan là gì",
    "Bảng tuần hoàn hóa học",
    "Phản ứng oxi hóa khử",
    "Axit và bazơ khác nhau sao",
    "Định luật Newton 1 2 3",
    "Động lượng là gì",
    "Năng lượng hạt nhân",
    "Phóng xạ là gì",
    "Biến đổi khí hậu nguyên nhân",
    "Hiệu ứng nhà kính",
    "Tầng ozone bị thủng",
    "Hóa học hữu cơ là gì",
    "Polyme là gì",
    "Nhiệt động lực học",
    "Entropy là gì",
    "Sóng điện từ là gì",
    "Quang phổ là gì",
    "Cơ học lượng tử",
    "Vật chất tối là gì",
    "Big Bang là gì",
    "Thiên hà Milky Way",
    "Sao chổi là gì",
    "Thiên thạch rơi xuống trái đất",
    "Tính giới hạn hàm số",
    "Chuỗi Taylor là gì",
    "Không gian Euclid",
    "Topo học là gì",
    "Lý thuyết đồ thị",
    "Thuật toán sắp xếp nhanh nhất",
    "Độ phức tạp O(n log n) là gì",
    "Turing machine là gì",
    "P và NP khác nhau sao",
    "Thuật toán Dijkstra",
    "Cây nhị phân tìm kiếm",
    "Hash table hoạt động thế nào",
    "Big O notation là gì",
    "Giải thuật tham lam",
    "Quy hoạch động",
    "Đệ quy là gì",
    "Bài toán người du lịch",
    "Lập trình tuyến tính",
    "Phương pháp Monte Carlo",
    "Hồi quy tuyến tính",
    "Mạng neural network",
    "Deep learning là gì",
    "Machine learning là gì",
    "Random forest algorithm",
    "Gradient descent",
    "Overfitting là gì",
    "Cross validation",
    "Tính sin 30 độ",
    "1 + 1 bằng mấy",
    "100 chia 7 bằng bao nhiêu",
    "Căn bậc 2 của 144",
    "Phân số 3/4 cộng 1/2",
    "Chuyển đổi đơn vị km sang m",
    "1 dặm bằng bao nhiêu km",
    "Nhiệt độ sôi của nước",
    "Áp suất khí quyển",
    "Khối lượng riêng của sắt",
    "Chu kỳ bán rã là gì",
    "Định luật bảo toàn năng lượng",
    "Sóng âm truyền qua chân không không",
    "Từ trường trái đất",
    "Tia X là gì",
    "Laser hoạt động thế nào",
    "Phản vật chất là gì",
    "Siêu dẫn là hiện tượng gì",
]

oos_cong_nghe = [
    "Python hay Java tốt hơn",
    "ChatGPT là gì",
    "AI có thay thế con người không",
    "Cách code website",
    "React hay Angular tốt hơn",
    "Học lập trình bắt đầu từ đâu",
    "iPhone 16 giá bao nhiêu",
    "Samsung Galaxy mới nhất",
    "Laptop nào tốt nhất 2025",
    "Windows hay MacOS tốt hơn",
    "Linux là gì",
    "Docker là gì",
    "Kubernetes dùng để làm gì",
    "Cloud computing là gì",
    "AWS hay Azure tốt hơn",
    "Cách tạo app di động",
    "Flutter hay React Native",
    "Backend là gì",
    "Frontend là gì",
    "Fullstack developer làm gì",
    "DevOps là gì",
    "Git là gì",
    "API là gì",
    "REST API là gì",
    "Database SQL hay NoSQL",
    "MongoDB là gì",
    "PostgreSQL hay MySQL",
    "Blockchain là gì",
    "NFT là gì",
    "Metaverse là gì",
    "5G nhanh hơn 4G bao nhiêu",
    "Internet of Things IoT",
    "Smart home là gì",
    "Robot có thay thế con người không",
    "Xe tự lái hoạt động thế nào",
    "Elon Musk là ai",
    "SpaceX là công ty gì",
    "Cách hack wifi",
    "Bảo mật mạng là gì",
    "VPN là gì",
    "Cách tạo website bán hàng",
    "SEO là gì",
    "Marketing online thế nào",
    "Photoshop hay Figma tốt hơn",
    "Cách edit video bằng gì",
    "TikTok kiếm tiền thế nào",
    "YouTube monetization",
    "Cách tạo game",
    "Unity hay Unreal Engine",
    "Cách fix bug trong code",
    "Stack Overflow là gì",
    "GitHub dùng để làm gì",
    "Tự học lập trình mất bao lâu",
    "Lương lập trình viên bao nhiêu",
    "Ngôn ngữ lập trình phổ biến nhất",
    "TypeScript là gì",
    "Rust hay Go tốt hơn",
    "Microservices là gì",
    "CI CD pipeline là gì",
    "Agile Scrum là gì",
    "Cách viết CV developer",
    "Phỏng vấn lập trình hỏi gì",
    "LeetCode là gì",
    "Data Science học gì",
    "Big Data là gì",
    "Hadoop vs Spark",
    "Power BI hay Tableau",
    "Excel nâng cao thế nào",
    "Cách tạo macro Excel",
    "Google Sheets vs Excel",
    "Notion hay Obsidian tốt hơn",
    "Cách dùng ChatGPT hiệu quả",
    "Gemini AI là gì",
    "Claude AI là gì",
    "Midjourney vẽ hình thế nào",
    "Stable Diffusion là gì",
    "Sora tạo video AI",
    "Deepfake là gì",
    "Cách phát hiện deepfake",
    "Cybersecurity làm gì",
    "Ethical hacking là gì",
]

oos_giai_tri = [
    "MU đá mấy giờ hôm nay",
    "Kết quả bóng đá tối qua",
    "Messi hay Ronaldo giỏi hơn",
    "World Cup tổ chức ở đâu",
    "SEA Games năm nay ở đâu",
    "Olympic mấy năm 1 lần",
    "Đội tuyển Việt Nam xếp hạng mấy",
    "V-League ai đang dẫn đầu",
    "Park Hang Seo còn dẫn dắt không",
    "Cầu thủ lương cao nhất thế giới",
    "NBA ai vô địch",
    "Tennis Grand Slam là gì",
    "F1 chặng tiếp theo ở đâu",
    "Phim hay nhất 2025",
    "Netflix phim gì đang hot",
    "Marvel movie tiếp theo",
    "Anime hay nhất mọi thời đại",
    "Manga One Piece kết thúc chưa",
    "Naruto hay Dragon Ball",
    "K-pop nhóm nào nổi nhất",
    "BTS giải tán chưa",
    "BLACKPINK comeback khi nào",
    "Sơn Tùng MTP ra bài mới chưa",
    "Jack J97 scandal gì",
    "The Voice mùa mới khi nào",
    "Rap Việt ai thắng",
    "Game hay nhất 2025",
    "GTA 6 ra mắt khi nào",
    "LMHT hay Valorant",
    "Minecraft server nào hay",
    "Roblox là gì",
    "PS5 hay Xbox tốt hơn",
    "Nintendo Switch game nào hay",
    "Free Fire hay PUBG",
    "Liên Quân rank mấy cao nhất",
    "Genshin Impact có hay không",
    "Streamer nào nổi tiếng nhất",
    "Theanh28 là ai",
    "Độ Mixi là ai",
    "PewPew còn stream không",
    "Phim Hàn hay nhất",
    "Phim Trung Quốc nào đáng xem",
    "Sách hay nên đọc",
    "Harry Potter mấy phần",
    "Truyện Conan bao giờ hết",
    "Webtoon hay nhất",
    "Podcast nghe gì hay",
    "Spotify hay Apple Music",
    "Cách tải nhạc miễn phí",
    "Karaoke bài nào dễ hát",
    "Tết có phim gì hay",
    "Phim kinh dị nào sợ nhất",
    "Ai là người giàu nhất Việt Nam",
    "Ai là người giàu nhất thế giới",
    "Lottery kết quả xổ số hôm nay",
    "Xổ số miền Bắc hôm nay",
    "Cá cược bóng đá",
    "Casino ở Việt Nam ở đâu",
    "Cờ bạc có hợp pháp không",
    "Trò chơi trực tuyến nào hay",
    "Board game nào vui",
    "Đố vui hại não",
    "Giải ô chữ thế nào",
    "Sudoku cách chơi",
    "Rubik cách giải nhanh",
    "Cách chơi cờ vua",
    "Cờ tướng mở đầu thế nào",
    "Thể thao điện tử esport",
    "Giải đấu Dota 2",
    "CS2 rank hệ thống mới",
    "Overwatch 2 có hay không",
    "Diablo 4 đáng mua không",
    "Baldur Gate 3 hay thế nào",
    "Elden Ring boss khó nhất",
    "Zelda Tears of the Kingdom",
    "Pokemon mới nhất",
    "Final Fantasy 7 Rebirth",
    "Cyberpunk 2077 đã fix bug chưa",
    "Hogwarts Legacy có hay không",
]

oos_ca_nhan = [
    "Tôi buồn quá",
    "Bạn có người yêu không",
    "Bạn bao nhiêu tuổi",
    "Bạn tên gì",
    "Bạn ở đâu",
    "Bạn có cảm xúc không",
    "Tôi nên làm gì với cuộc đời",
    "Ý nghĩa cuộc sống là gì",
    "Làm sao để hạnh phúc",
    "Tôi thất tình rồi",
    "Cách quên người yêu cũ",
    "Tôi cô đơn quá",
    "Bạn có biết yêu không",
    "Kể chuyện cười đi",
    "Hát cho tôi nghe đi",
    "Viết thơ tình cho tôi",
    "Bạn thông minh lắm",
    "Bạn ngu quá",
    "Tôi ghét bạn",
    "Tôi yêu bạn",
    "Bạn có thể kết hôn không",
    "Mày là robot à",
    "Bạn có ý thức không",
    "Ai tạo ra bạn",
    "Bạn được lập trình bằng gì",
    "Bạn có thể tự học không",
    "Bạn nghĩ gì về con người",
    "Bạn có mơ không",
    "Bạn có sợ bị tắt không",
    "Tại sao bạn tồn tại",
    "Bạn có linh hồn không",
    "Tôi muốn nói chuyện phiếm",
    "Kể cho tôi nghe gì đi",
    "Bạn biết hát không",
    "Bạn biết nhảy không",
    "Bạn thích màu gì",
    "Bạn thích ai nhất",
    "Con vật nào bạn thích",
    "Mùa nào bạn thích nhất",
    "Bạn có bạn bè không",
    "Bạn có gia đình không",
    "Bạn ăn gì không",
    "Bạn ngủ không",
    "Bạn có mệt không",
    "Hôm nay bạn thế nào",
    "Bạn vui không",
    "Tôi stress quá làm sao",
    "Cách giảm stress",
    "Tôi không muốn đi làm",
    "Sếp tôi khó chịu lắm",
    "Đồng nghiệp hay nói xấu",
    "Tôi muốn nghỉ việc",
    "Cách xin tăng lương",
    "Tôi nên chọn nghề gì",
    "Tương lai tôi thế nào",
    "Xem bói cho tôi",
    "Cung hoàng đạo tôi là gì",
    "Tử vi hôm nay",
    "Phong thủy nhà cửa",
    "Giải mộng cho tôi",
    "Tôi mơ thấy rắn",
    "Số may mắn hôm nay",
    "Xem tướng số tôi",
    "Tôi sinh năm 1995 mệnh gì",
    "Tuổi nào hợp nhau",
    "Ngày cưới tốt tháng này",
    "Cách cua gái",
    "Cách tỏ tình",
    "Bạn gái giận làm sao",
    "Chồng ngoại tình phải làm sao",
    "Ly hôn thủ tục thế nào",
    "Nuôi con sau ly hôn",
    "Cách dạy con ngoan",
    "Con tôi không chịu học",
    "Tuổi dậy thì con gái",
    "Mang thai tháng đầu cần biết gì",
    "Cách giảm cân nhanh",
    "Tập gym hay chạy bộ",
    "Yoga có tốt không",
    "Thiền có lợi gì",
]

oos_y_te = [
    "Tôi bị đau đầu uống thuốc gì",
    "Covid có hết chưa",
    "Triệu chứng cảm cúm",
    "Cách hạ sốt nhanh",
    "Đau bụng nên ăn gì",
    "Bị ho lâu ngày",
    "Dị ứng thức ăn làm sao",
    "Cách chữa mụn",
    "Da khô phải làm sao",
    "Rụng tóc uống thuốc gì",
    "Tiểu đường ăn gì",
    "Huyết áp cao cách điều trị",
    "Ung thư phổi triệu chứng",
    "Trầm cảm là gì",
    "Rối loạn lo âu làm sao",
    "Mất ngủ uống gì",
    "Vitamin nào nên uống hàng ngày",
    "Canxi cho người lớn tuổi",
    "Tiêm vaccine covid mũi 3",
    "Bệnh tay chân miệng",
    "Sốt xuất huyết triệu chứng",
    "Cách phòng ngừa bệnh tim",
    "Cholesterol cao ăn gì",
    "Gout kiêng gì",
    "Viêm loét dạ dày",
    "Sỏi thận có nguy hiểm không",
    "Đau lưng mãn tính",
    "Thoát vị đĩa đệm",
    "Cận thị có chữa được không",
    "Niềng răng bao lâu",
    "Nhổ răng khôn có đau không",
    "Viêm xoang chữa thế nào",
    "Viêm họng uống gì",
    "Hen suyễn phong khám nào",
    "Bệnh phổi tắc nghẽn",
    "Viêm gan B có lây không",
    "Xét nghiệm máu bao lâu có kết quả",
    "Bệnh viện nào tốt nhất",
    "Bác sĩ chuyên khoa tim",
    "BHYT khám ở đâu",
    "Chi phí phẫu thuật mắt",
    "Ghép thận chi phí bao nhiêu",
    "Cấy ghép tóc ở đâu",
    "Phẫu thuật thẩm mỹ mũi",
    "Botox có an toàn không",
    "Filler môi bao tiền",
    "Giảm cân bằng phương pháp nào",
    "Detox có tốt không",
    "Keto diet là gì",
    "Intermittent fasting",
    "Collagen uống có tác dụng không",
    "Thực phẩm chức năng có tốt không",
    "Thuốc bổ gan nào tốt",
    "Cách bỏ thuốc lá",
    "Rượu bia có hại gì",
    "Ma túy gây hại thế nào",
    "Cách cai nghiện game",
    "Sức khỏe tâm thần là gì",
    "Tâm lý trị liệu ở đâu",
    "Mindfulness là gì",
    "Sơ cứu khi bị bỏng",
    "Bị rắn cắn làm gì",
    "Cách sơ cứu đuối nước",
    "Hô hấp nhân tạo thế nào",
    "Ép tim ngoài lồng ngực",
    "Cách xử lý khi bị gãy xương",
    "Chảy máu cam làm sao",
    "Bị ong đốt bôi gì",
    "Dị ứng thuốc triệu chứng",
    "Sốc phản vệ là gì",
    "Tác dụng phụ của kháng sinh",
    "Kháng kháng sinh là gì",
    "Thuốc giảm đau nào an toàn",
    "Paracetamol hay Ibuprofen",
    "Liều lượng thuốc cho trẻ em",
    "Thuốc hết hạn có uống được không",
    "Đông y hay tây y",
    "Châm cứu chữa bệnh gì",
    "Bấm huyệt có tác dụng gì",
    "Xoa bóp giảm đau",
]

oos_tai_chinh = [
    "Bitcoin giá bao nhiêu",
    "Ethereum có nên mua không",
    "Nên đầu tư gì năm 2025",
    "Chứng khoán hôm nay thế nào",
    "VN-Index bao nhiêu điểm",
    "Cổ phiếu nào nên mua",
    "Vàng giá bao nhiêu",
    "Nên mua vàng hay đất",
    "Lãi suất ngân hàng nào cao nhất",
    "Gửi tiết kiệm ngân hàng nào",
    "Cách mở tài khoản chứng khoán",
    "Quỹ đầu tư là gì",
    "ETF là gì",
    "Cách tính lãi suất kép",
    "Forex là gì",
    "Cách đầu tư bất động sản",
    "Thuế thu nhập cá nhân tính sao",
    "Cách khai thuế online",
    "Bảo hiểm nhân thọ nào tốt",
    "Bảo hiểm xe máy bao nhiêu",
    "Vay ngân hàng cần gì",
    "Lãi suất vay mua nhà",
    "Trả góp 0% có thật không",
    "Tín dụng đen là gì",
    "Cách quản lý chi tiêu",
    "Tài chính cá nhân cho người trẻ",
    "Cách tiết kiệm tiền hiệu quả",
    "Quỹ khẩn cấp bao nhiêu đủ",
    "Startup cần bao nhiêu vốn",
    "Cách gọi vốn đầu tư",
    "Shark Tank Việt Nam",
    "Angel investor là gì",
    "Venture capital là gì",
    "IPO là gì",
    "Cổ tức là gì",
    "P/E ratio nghĩa là gì",
    "Margin trading rủi ro gì",
    "Short selling là gì",
    "Stablecoin là gì",
    "DeFi là gì",
    "Wallet crypto nào an toàn",
    "Cách mua Bitcoin ở Việt Nam",
    "Sàn giao dịch crypto nào uy tín",
    "Tiền số có hợp pháp ở VN không",
    "Ponzi scheme là gì",
    "MLM đa cấp là gì",
    "Cách nhận biết lừa đảo tài chính",
    "Binance có an toàn không",
    "PayPal dùng ở Việt Nam được không",
    "Ví MoMo an toàn không",
    "ZaloPay hay MoMo",
    "Cách kiếm tiền online",
    "Freelancer thu nhập bao nhiêu",
    "Dropshipping là gì",
    "Affiliate marketing kiếm tiền sao",
    "Cách kiếm tiền từ blog",
    "Thu nhập thụ động là gì",
    "Passive income từ đâu",
    "Cách đầu tư vàng online",
    "Future contract là gì",
    "Options trading cho người mới",
    "Swing trading là gì",
    "Day trading có lời không",
    "Copy trading an toàn không",
    "Robo advisor là gì",
    "Fintech công ty nào nổi bật",
    "Neobank là gì",
    "Ngân hàng số nào tốt nhất Việt Nam",
    "Timo hay Cake by VP Bank",
    "Mở thẻ tín dụng cần gì",
    "Cashback thẻ tín dụng nào cao",
    "Điểm tín dụng CIC là gì",
    "Nợ xấu ảnh hưởng gì",
    "Phá sản cá nhân ở Việt Nam",
    "Thuế giá trị gia tăng VAT",
    "Thuế nhập khẩu xe ô tô",
    "Giá xăng hôm nay bao nhiêu",
    "Giá điện tăng bao nhiêu",
    "Giá gas hôm nay",
]

oos_giao_duc = [
    "Điểm chuẩn Bách Khoa bao nhiêu",
    "IELTS 7.0 khó không",
    "Cách học TOEIC hiệu quả",
    "Học bổng du học Mỹ",
    "Du học Nhật Bản cần gì",
    "Đại học nào tốt nhất Việt Nam",
    "Ngành nào ra trường dễ xin việc",
    "Cách viết luận văn thạc sĩ",
    "Cách làm đồ án tốt nghiệp",
    "Học thạc sĩ ở đâu",
    "PhD mất bao lâu",
    "Cách học hiệu quả",
    "Phương pháp Pomodoro",
    "Mind map là gì",
    "Cách ghi nhớ nhanh",
    "Kỹ năng mềm quan trọng nhất",
    "Cách thuyết trình hay",
    "Cách viết CV xin việc",
    "Phỏng vấn xin việc nên nói gì",
    "Gap year nên làm gì",
    "Thi đại học khó không",
    "Cách làm bài thi trắc nghiệm",
    "Thi THPT quốc gia môn nào khó nhất",
    "Nên học ban A hay ban D",
    "Thi đánh giá năng lực là gì",
    "SAT là gì",
    "GRE thi ở đâu",
    "GMAT cần bao nhiêu điểm",
    "Harvard yêu cầu gì",
    "MIT học phí bao nhiêu",
    "Oxford hay Cambridge tốt hơn",
    "Đại học FPT học phí bao nhiêu",
    "RMIT có đắt không",
    "Trường quốc tế nào tốt",
    "Mầm non quốc tế hay công lập",
    "Cách dạy con học toán",
    "Montessori là gì",
    "STEM education là gì",
    "Homeschool ở Việt Nam",
    "Trung tâm tiếng Anh nào tốt",
    "Học tiếng Nhật khó không",
    "Học tiếng Hàn bao lâu",
    "Tiếng Trung nên bắt đầu từ đâu",
    "Duolingo có hiệu quả không",
    "Coursera có chứng chỉ không",
    "Udemy khóa học nào hay",
    "EdX miễn phí không",
    "Học online có hiệu quả không",
    "Cách tự học ngoại ngữ",
    "Flashcard Anki dùng thế nào",
    "Cách đọc sách hiệu quả",
    "Speed reading là gì",
    "Tư duy phản biện là gì",
    "Logic học là gì",
    "Triết học nhập môn",
    "Tâm lý học hành vi",
    "Xã hội học là gì",
    "Kinh tế học vi mô",
    "Kinh tế học vĩ mô",
    "Cung cầu thị trường",
    "Quy luật giá trị",
    "Lý thuyết trò chơi game theory",
    "Nghịch lý tù nhân",
    "Hiệu ứng bướm là gì",
    "Lý thuyết hỗn loạn",
    "Lịch sử Việt Nam tóm tắt",
    "Triều đại nào dài nhất Việt Nam",
    "Vua nào giỏi nhất lịch sử",
    "Chiến thắng Bạch Đằng năm nào",
    "Thăng Long thành lập năm nào",
    "Nguyễn Du viết Truyện Kiều năm nào",
    "Văn học Việt Nam thời kỳ nào hay nhất",
    "Thơ Xuân Diệu nổi tiếng nhất",
    "Truyện ngắn Nam Cao",
    "Bài thơ Tây Tiến của ai",
    "Phân tích Chí Phèo",
    "Nghị luận xã hội viết thế nào",
    "Văn nghị luận văn học",
    "Cách viết đoạn văn nghị luận",
    "Thi học sinh giỏi quốc gia",
    "Olympic quốc tế toán học",
]

oos_vo_nghia = [
    "asdfgh",
    "jkl;'",
    "qwerty",
    "zxcvbnm",
    "abc 123",
    "hahaha",
    "hehehehe",
    "hihi",
    "lol",
    "lmao",
    "???",
    "!!!",
    "...",
    "ok",
    "hmm",
    "ừ",
    "uh",
    "ahh",
    "zzz",
    "test",
    "test 123",
    "hello world",
    "a",
    "b",
    "aa bb cc",
    "1234567890",
    "aaaaaaa",
    "bbbbb",
    "blah blah",
    "gì vậy",
    "cái gì",
    "sao vậy",
    "ơ",
    "á",
    "ủa",
    "hả",
    "what",
    "why",
    "how",
    "nothing",
    "never mind",
    "thôi",
    "bỏ đi",
    "không biết",
    "kệ",
    "mệt",
    "chán",
    "buồn cười",
    "xàm",
    "vớ vẩn",
    "nhảm nhí",
    "linh tinh",
    "lung tung",
    "quên rồi",
    "nói bậy",
    "đùa thôi",
    "tào lao",
    "bla bla bla",
    "random text here",
    "dsfkjshdfkj",
    "aoskdoaskd",
    "fjdkslfjds",
    "vkjxncvjk",
    "qqqqqqq",
    "wwwwww",
    "eeeee",
    "rrrrrr",
    "ttttt",
    "yyyyy",
    "uuuuu",
    "iiiii",
    "ooooo",
    "ppppp",
    "đồ ngốc",
    "con bot ngu",
    "mày ngu lắm",
    "thằng ngu",
    "nói linh tinh",
    "cái quái gì vậy",
    "wtf",
    "omg",
    "bruh",
    "oof",
    "yolo",
    "swag",
    "skibidi",
    "cap",
    "no cap",
    "sus",
    "slay",
    "based",
    "cringe",
    "ratio",
    "L",
    "W",
    "gg",
    "ez",
    "noob",
    "pro",
    "tryhard",
    "camper",
    "lag",
    "ping cao quá",
]

# ==============================================================================
# 1b. EDGE CASES BỔ SUNG (từ generate_oos_edge_cases.py & generate_oos_crypto.py)
# ==============================================================================

# --- Pattern "Ai là / Ai phát minh" → tránh SVM nhầm thành chao_hoi ---
oos_edge_ai_la = [
    "Ai phát minh ra bóng đèn",
    "Ai phát minh ra điện",
    "Ai là CEO của Apple",
    "Ai sáng lập Facebook",
    "Ai có nhiều tiền nhất Việt Nam",
    "Ai đã từng lên mặt trăng",
    "Ai viết truyện Kiều",
    "Ai là vua cuối cùng triều Nguyễn",
    "Ai phát hiện ra châu Mỹ",
    "Ai là người đứng đầu Liên Hợp Quốc",
    "Ai đã phát minh ra internet",
    "Ai sáng chế ra máy bay",
    "Ai là huấn luyện viên đội tuyển Việt Nam",
    "Ai là ca sĩ nổi tiếng nhất Việt Nam",
    "Ai đã đoạt giải Nobel năm nay",
]

# --- Y tế chứa "uống" → tránh SVM nhầm thành tim_mon_an ---
oos_edge_uong_thuoc = [
    "Uống thuốc gì trị cảm cúm",
    "Bị sốt nên uống thuốc gì",
    "Đau bụng uống thuốc gì cho nhanh khỏi",
    "Uống thuốc gì để hạ sốt",
    "Bị ho uống gì cho hết",
    "Đau răng uống thuốc gì",
    "Bị tiểu đường uống thuốc gì",
    "Uống gì để giảm cân nhanh",
    "Bị mất ngủ uống thuốc gì",
    "Đau lưng uống thuốc gì",
    "Bị dị ứng uống thuốc gì",
    "Uống thuốc gì trị mụn",
    "Bị táo bón uống gì cho tốt",
    "Huyết áp cao uống thuốc gì",
]

# --- Crypto/Finance bổ sung → tránh NER nhầm "ốc" trong Bitcoin ---
oos_crypto_extra = [
    "Bitcoin hôm nay giá bao nhiêu",
    "Tỷ giá Bitcoin",
    "Giá Bitcoin hiện tại",
    "Ethereum giá bao nhiêu",
    "Giá crypto hôm nay",
    "Giá vàng hôm nay bao nhiêu",
    "Giá đô la bao nhiêu",
    "Dogecoin có nên mua không",
    "Solana giá bao nhiêu",
    "Bitcoin có phải lừa đảo không",
    "Giá cổ phiếu Vinamilk",
]

# ==============================================================================
# 2. DỮ LIỆU BỔ SUNG CHO INTENT GIAO TIẾP NHỎ (~142 câu)
# ==============================================================================

chao_hoi_extra = [
    "Ê",
    "Alo",
    "Hey",
    "Hey bot",
    "Ê chatbot",
    "Yo",
    "Chào buổi trưa",
    "Chào bạn ơi",
    "Bot ơi",
    "Mình chào bạn",
    "Chào nhé",
    "Hi bạn",
    "Hello bạn",
    "Xin chào bạn nhé",
    "Chào chatbot",
    "Chào AI",
    "Hế lô",
    "Hê lô",
    "Hai",
    "Helu",
    "Chào bạn nha",
    "Chào xin chào",
    "Chatbot ơi",
    "Ơi bot",
    "Có ai không",
    "Bot đâu rồi",
    "Có ai ở đây không",
    "Chào buổi sáng nha",
    "Chào buổi chiều nha",
    "Good night",
    "Xin chào buổi sáng",
    "Chào mừng",
    "Hí",
    "Hí bạn",
    "Ohayo",
    "Konnichiwa",
]

cam_on_extra = [
    "Tuyệt vời",
    "Hay quá",
    "Cảm ơn bạn nhiều lắm",
    "Quá tuyệt vời",
    "Cảm ơn rất nhiều nhé",
    "Thank you very much",
    "Cảm ơn bot nhiều",
    "Cảm ơn AI nhé",
    "Tks",
    "Tks bạn",
    "Thks",
    "Cám ơn",
    "Cám ơn nhiều",
    "Cám ơn nhé bạn",
    "Thankiu",
    "Thanku",
    "Cảm ơn chatbot nhé",
    "Mình cảm ơn bạn",
    "Cảm ơn bạn rất nhiều",
    "Biết ơn bạn",
    "Ghi nhận nha",
    "Mình hiểu rồi cảm ơn",
    "Ok cảm ơn",
    "Oke thanks",
    "Cảm ơn nha bạn",
    "Dạ cảm ơn",
    "Cảm ơn ạ",
    "Thanks nha",
    "Thanks nhé",
    "Thank you nhé",
    "Cảm ơn đã giúp",
    "Bạn giúp ích nhiều lắm",
    "Rất hữu ích cảm ơn",
    "Perfect thanks",
    "Great thanks",
    "Wonderful cảm ơn",
]

tam_biet_extra = [
    "Ngủ ngon",
    "Tạm biệt nha",
    "Thôi mình đi",
    "Mình đi đây nha",
    "Bye nha",
    "Bye bạn",
    "Bai bai",
    "Bai",
    "Tạm biệt bạn nha",
    "Chào bạn mình đi đây",
    "Thôi bye",
    "Gặp lại sau nhé",
    "Mai gặp lại",
    "Hẹn gặp lại nhé bạn",
    "See ya",
    "Gotta go",
    "Mình phải đi rồi",
    "Tôi đi đây nhé",
    "Bạn ở lại nhé",
    "Chúc ngủ ngon",
    "Ngủ ngon nhé",
    "Chúc buổi tối vui vẻ",
    "Chào tạm biệt nha",
    "Good night bot",
    "Goodbye nha",
    "Thôi mình không hỏi nữa",
    "Hết rồi bye",
    "Ok bye",
    "Oke tạm biệt",
    "Chào nhé tạm biệt",
    "Mình đi ngủ đây",
    "Thôi được rồi bye",
    "Mình hiểu rồi bye",
    "Ok tạm biệt nhé",
    "Sayonara",
]

hoi_thong_tin_extra = [
    "Bot biết gì",
    "Dùng sao",
    "Chức năng",
    "Bot làm được gì",
    "Chatbot có chức năng gì",
    "Mình hỏi gì được",
    "Bot trả lời được gì",
    "Hướng dẫn dùng chatbot",
    "Cách dùng bot",
    "Bot hỗ trợ những gì",
    "Chatbot này dùng để làm gì",
    "Tôi có thể hỏi gì bạn",
    "Bạn có thể giúp tôi gì",
    "Mô tả về bạn",
    "Giới thiệu chatbot",
    "Chatbot này là gì",
    "Công dụng của chatbot",
    "Hỏi bot cái gì được",
    "Bot biết tìm gì",
    "Tính năng chatbot",
    "Bot thông minh không",
    "Chatbot AI hả",
    "Bot tìm đồ ăn được không",
    "Bot tìm khách sạn được không",
    "Mình muốn biết về chatbot",
    "Bạn là AI gì",
    "SavoryTrip là gì",
    "Chatbot du lịch hả",
    "Bot ẩm thực phải không",
    "Giúp tôi hiểu cách dùng",
    "Xem menu chức năng",
    "Danh sách tính năng",
    "Bot có bao nhiêu chức năng",
    "Feature của chatbot",
    "Chatbot guide",
]

# ==============================================================================
# 3. AGGREGATE & APPEND VÀO FILE CSV
# ==============================================================================

all_oos = []
for text in oos_chinh_tri: all_oos.append((text, "out_of_scope"))
for text in oos_khoa_hoc_toan: all_oos.append((text, "out_of_scope"))
for text in oos_cong_nghe: all_oos.append((text, "out_of_scope"))
for text in oos_giai_tri: all_oos.append((text, "out_of_scope"))
for text in oos_ca_nhan: all_oos.append((text, "out_of_scope"))
for text in oos_y_te: all_oos.append((text, "out_of_scope"))
for text in oos_tai_chinh: all_oos.append((text, "out_of_scope"))
for text in oos_giao_duc: all_oos.append((text, "out_of_scope"))
for text in oos_vo_nghia: all_oos.append((text, "out_of_scope"))
for text in oos_edge_ai_la: all_oos.append((text, "out_of_scope"))
for text in oos_edge_uong_thuoc: all_oos.append((text, "out_of_scope"))
for text in oos_crypto_extra: all_oos.append((text, "out_of_scope"))

all_extra = []
for text in chao_hoi_extra: all_extra.append((text, "chao_hoi"))
for text in cam_on_extra: all_extra.append((text, "cam_on"))
for text in tam_biet_extra: all_extra.append((text, "tam_biet"))
for text in hoi_thong_tin_extra: all_extra.append((text, "hoi_thong_tin"))

all_new = all_oos + all_extra

print(f"=== THONG KE DU LIEU MOI ===")
print(f"  out_of_scope: {len(all_oos)} cau")
print(f"  chao_hoi (bo sung): {len(chao_hoi_extra)} cau")
print(f"  cam_on (bo sung): {len(cam_on_extra)} cau")
print(f"  tam_biet (bo sung): {len(tam_biet_extra)} cau")
print(f"  hoi_thong_tin (bo sung): {len(hoi_thong_tin_extra)} cau")
print(f"  TONG CONG: {len(all_new)} cau moi")

# Đọc dữ liệu hiện tại để chống trùng lặp (dedup)
existing_texts = set()
if os.path.exists(DATASET_PATH):
    with open(DATASET_PATH, 'r', encoding='utf-8-sig') as f:
        reader = csv.reader(f)
        next(reader, None)  # skip header
        for row in reader:
            if row:
                existing_texts.add(row[0].strip())

# Lọc ra chỉ những câu CHƯA có trong dataset
new_only = [(text, intent) for text, intent in all_new if text.strip() not in existing_texts]
skipped = len(all_new) - len(new_only)

# Append to CSV
with open(DATASET_PATH, 'a', encoding='utf-8-sig', newline='') as f:
    writer = csv.writer(f)
    for text, intent in new_only:
        writer.writerow([text, intent])

print(f"\nDa append {len(new_only)} cau moi vao {DATASET_PATH} (bo qua {skipped} cau trung lap)")

# Read back to verify
with open(DATASET_PATH, 'r', encoding='utf-8-sig') as f:
    reader = csv.reader(f)
    next(reader)  # skip header
    counts = collections.Counter(row[-1] for row in reader if row)

print(f"\n=== PHAN BO SAU KHI CAP NHAT ===")
total = sum(counts.values())
for intent, count in counts.most_common():
    print(f"  {intent}: {count} cau ({count*100//total}%)")
print(f"  TONG: {total} cau")
