# -*- coding: utf-8 -*-
"""
Script bổ sung dữ liệu Phase 4:
- Tăng 4 conversation intents lên ~200 mẫu/cái
- Tăng 3 intent mới (hoi_gia, danh_gia, so_sanh) lên ~150 mẫu/cái

Chạy: python generate_phase4_data.py
Output: Append vào data/intent_dataset.csv (có dedup)
"""

import csv
import os
import collections

# Đường dẫn dataset
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATASET_PATH = os.path.join(SCRIPT_DIR, "data", "intent_dataset.csv")

# ==============================================================================
# 1. BỔ SUNG CONVERSATION INTENTS
# ==============================================================================

# chao_hoi: cần thêm ~30 mẫu (170→200)
# Tập trung vào: teen code, mix tiếng Anh, ngữ cảnh cụ thể, câu dài
chao_hoi_phase4 = [
    "chào bạn chatbot",
    "xin chào SavoryTrip",
    "ê ơi có ai không",
    "hey hey",
    "hế lô bạn ơi",
    "chào nha bạn ơi",
    "mình chào bạn nè",
    "xin chào buổi chiều",
    "chào buổi sáng bạn nhé",
    "a lô ai đấy",
    "alo alo",
    "hello hello",
    "hi hi",
    "chào bot nè",
    "ê bot ơi mình cần giúp đỡ",
    "xin chào mình mới đến",
    "chào mọi người",
    "chào bạn mình muốn hỏi",
    "hi mình cần tìm quán ăn",
    "hello bot giúp mình với",
    "chào nhé mình hỏi chút",
    "hey mình muốn tìm đồ ăn",
    "oi bot giúp mình cái",
    "ê bạn ơi giúp mình",
    "xin chào tôi muốn hỏi",
    "chào bạn tôi cần gợi ý",
    "yo yo",
    "what's up",
    "chào buổi tối nhé bạn",
    "hi there",
    "hey can you help me",
    "chào bạn mới biết chatbot này",
    "ê có ai online không",
    "bot có ở đây không",
    "chào buổi xế chiều",
]

# cam_on: cần thêm ~60 mẫu (140→200)
cam_on_phase4 = [
    "cảm ơn bạn rất nhiều nha",
    "thanks nha chatbot",
    "cảm ơn đã gợi ý",
    "cảm ơn gợi ý quán ăn",
    "tks bro",
    "thank u",
    "cảm ơn nhiều lắm luôn",
    "cảm ơn bot đã giúp",
    "hay quá cảm ơn bạn",
    "quá tuyệt cảm ơn nhé",
    "cảm ơn đã tìm giúp",
    "ok cảm ơn nha",
    "được rồi cảm ơn",
    "mình hiểu rồi thanks",
    "tks nhé bạn",
    "cảm ơn lắm á",
    "cảm ơn nha bạn tuyệt lắm",
    "thank you nha bot",
    "cảm ơn rất nhiều ạ",
    "vâng cảm ơn nhé",
    "dạ em cảm ơn ạ",
    "cảm ơn anh chị chatbot",
    "oke cảm ơn nha bạn",
    "hay quá thanks bạn",
    "ok rồi cảm ơn nhé",
    "quá xịn cảm ơn",
    "mình rất hài lòng cảm ơn",
    "tuyệt vời cảm ơn bạn nhé",
    "gợi ý hay lắm cảm ơn",
    "bot giỏi quá cảm ơn",
    "oke fine cảm ơn nha",
    "good job cảm ơn bot",
    "cảm ơn đã gợi ý quán",
    "cảm ơn bạn gợi ý hay",
    "thank you so much nha",
    "rất biết ơn bạn",
    "cảm ơn chatbot nhé bạn",
    "quá ok cảm ơn",
    "cảm ơn bạn nhé tuyệt",
    "đúng cái mình cần cảm ơn",
    "cảm ơn mình sẽ thử",
    "thanks mình đi ăn đây",
    "cảm ơn sẽ ghé thử",
    "tks sẽ đến quán này",
    "cảm ơn gợi ý tuyệt vời",
    "thank bạn nhiều",
    "cảm ơn nhé rất hữu ích",
    "ok tks nha bạn",
    "cảm ơn bạn đã giúp mình",
    "thanks đã trả lời",
    "cảm ơn phản hồi nhanh",
    "tks nha chatbot ơi",
    "thankiu bạn nhiều",
    "cảm ơn nha mình đi đây",
    "oke tks bye",
    "cảm ơn nhé hẹn gặp lại",
    "ok cảm ơn gợi ý nhé",
    "cảm ơn bạn lần nữa",
    "rất cảm ơn chatbot",
    "thật sự cảm ơn bạn",
]

# tam_biet: cần thêm ~60 mẫu (140→200)
tam_biet_phase4 = [
    "tạm biệt chatbot nhé",
    "bye nha bot ơi",
    "thôi mình đi ăn đây",
    "mình đi đây tạm biệt",
    "bye bye nha bạn",
    "tạm biệt nha hẹn gặp lại",
    "chào nhé mình đi rồi",
    "ok bye nhé bạn",
    "bai bai nha",
    "oke bye bạn",
    "thôi mình off đây",
    "mình ra ngoài đây nhé",
    "hẹn gặp lại lần sau nha",
    "mai mình quay lại nhé",
    "tạm biệt nhé cảm ơn",
    "bye bye hẹn gặp lại",
    "see you later",
    "see you nha",
    "gotta go bye",
    "thôi bye nhé",
    "ok tạm biệt nha bot",
    "mình hỏi đủ rồi bye",
    "cảm ơn bye nha",
    "thanks bye",
    "đủ rồi bye bye",
    "ok mình đi nhé",
    "tạm biệt bot nhé",
    "goodbye nha bạn",
    "good night nha bot",
    "ngủ ngon nha chatbot",
    "chúc ngủ ngon nhé bot",
    "thôi không hỏi nữa bye",
    "hết câu hỏi rồi bye",
    "oke đủ rồi bye nhé",
    "mình tìm được rồi bye",
    "ok bye mình đi ăn đây",
    "thanks bye bye",
    "mình phải đi rồi bye nha",
    "bai nha chatbot",
    "bye chatbot nhé",
    "tạm biệt SavoryTrip",
    "bye SavoryTrip",
    "ok hẹn lần sau nhé",
    "mình đi ngủ rồi bye",
    "khuya rồi bye nhé",
    "thôi muộn rồi bye",
    "bye nhé mình về",
    "tạm biệt nha bạn ơi",
    "chào tạm biệt nha bot",
    "bye bye thanku",
    "adios",
    "ciao",
    "sayonara nha",
    "mata ne",
    "chúc bạn tối vui vẻ bye",
    "ok bye mình đi",
    "thôi nhé tạm biệt",
    "hết rồi tạm biệt nhé",
    "ok tạm biệt nhé bạn",
    "bye I gotta go",
]

# hoi_thong_tin: cần thêm ~80 mẫu (120→200)
hoi_thong_tin_phase4 = [
    "bot này là cái gì vậy",
    "chatbot này dùng để làm gì vậy",
    "mình có thể hỏi bot những gì",
    "bot giúp được gì cho mình",
    "cho mình hỏi bot có tính năng gì",
    "bot tìm kiếm được món ăn không",
    "chatbot có gợi ý du lịch không",
    "hướng dẫn mình cách dùng chatbot",
    "cách sử dụng bot thế nào",
    "bot hoạt động như thế nào",
    "mình mới dùng chatbot lần đầu",
    "cho mình biết thông tin về bot",
    "giới thiệu chatbot đi",
    "bạn là robot gì vậy",
    "bạn là ai và làm gì",
    "cho mình biết bạn là gì",
    "chatbot SavoryTrip là gì",
    "SavoryTrip chatbot làm được những gì",
    "bot có dữ liệu bao nhiêu quán",
    "chatbot biết bao nhiêu địa điểm",
    "bot tìm được bao nhiêu quán ăn",
    "database của bot lớn không",
    "bot có thông minh không",
    "AI của chatbot là gì",
    "bot sử dụng công nghệ gì",
    "chatbot chạy bằng gì",
    "thuật toán chatbot là gì",
    "mình muốn biết về chatbot này",
    "kể cho mình nghe về bạn đi",
    "bạn biết làm gì hả",
    "menu chức năng bot",
    "danh sách tính năng chatbot",
    "bot có bao nhiêu chức năng",
    "tất cả tính năng của bot",
    "help me",
    "help",
    "trợ giúp",
    "hướng dẫn sử dụng",
    "cho mình help",
    "guide cho mình",
    "bot hỗ trợ gì",
    "chatbot hỗ trợ những gì nhỉ",
    "bạn có thể giúp mình tìm đồ ăn không",
    "bot có tìm được địa điểm du lịch không",
    "chatbot gợi ý quán cà phê được không",
    "bot so sánh món ăn được không",
    "chatbot xem giá được không",
    "bot có review quán ăn không",
    "chatbot có xem đánh giá không",
    "bot tìm quán gần đây được không",
    "chatbot có chức năng tìm kiếm không",
    "mình hỏi gì thì bot trả lời được",
    "bot có biết quán nào ngon không",
    "chatbot có tìm được khách sạn không",
    "bot có giới thiệu nhà hàng không",
    "SavoryTrip có gì hay",
    "ai tạo ra chatbot này",
    "chatbot này ai làm",
    "bot của ai vậy",
    "đây là dự án gì",
    "chatbot này thuộc dự án nào",
    "mục đích của chatbot",
    "tại sao có chatbot này",
    "ai phát triển bot này",
    "chatbot phiên bản mấy",
    "version chatbot là gì",
    "cập nhật mới nhất của bot",
    "chatbot có gì mới",
    "hướng dẫn cho người mới",
    "mình chưa biết dùng chatbot",
    "dùng bot lần đầu hướng dẫn đi",
    "tutorial chatbot",
    "chatbot instructions",
    "how to use this bot",
    "what can you do",
    "what is this chatbot",
    "bot features",
    "tell me about yourself",
    "describe yourself",
    "who are you",
]

# ==============================================================================
# 2. BỔ SUNG 3 INTENT MỚI
# ==============================================================================

# hoi_gia: cần thêm ~70 mẫu (80→150)
hoi_gia_phase4 = [
    "giá bao nhiêu vậy",
    "quán này đắt không",
    "ăn ở đây hết bao nhiêu",
    "giá cả thế nào bạn",
    "bún chả giá bao nhiêu tiền",
    "cơm tấm giá bao nhiêu",
    "một tô phở giá bao nhiêu",
    "bánh mì giá bao nhiêu",
    "giá quán ăn này thế nào",
    "chi phí ăn uống ở đây",
    "túi tiền học sinh ăn ở đâu",
    "quán nào giá rẻ",
    "quán ăn giá bình dân",
    "ăn gì rẻ ở Sài Gòn",
    "phở giá rẻ ở đâu",
    "bún bò giá bao nhiêu",
    "giá trung bình quán này",
    "tầm giá bao nhiêu",
    "khoảng giá ăn uống ở đây",
    "giá mỗi phần bao nhiêu",
    "quán buffet giá bao nhiêu",
    "lẩu giá bao nhiêu một nồi",
    "giá cà phê ở đây",
    "trà sữa giá bao nhiêu",
    "nước mía bao nhiêu tiền",
    "giá sinh tố ở quán này",
    "ăn hải sản giá bao nhiêu",
    "giá vé vào cửa bao nhiêu",
    "khách sạn giá bao nhiêu một đêm",
    "giá phòng resort khoảng bao nhiêu",
    "homestay giá bao nhiêu",
    "du lịch Đà Lạt tốn bao nhiêu",
    "chi phí đi Nha Trang",
    "đi Phú Quốc hết bao nhiêu",
    "budget du lịch Đà Nẵng",
    "tốn khoảng bao nhiêu tiền",
    "giá có đắt không",
    "mắc không vậy",
    "quán này mắc hay rẻ",
    "ăn ở đây có đắt không bạn",
    "giá có phải chăng không",
    "quán này giá sinh viên không",
    "có menu giá không",
    "bảng giá quán này",
    "ăn hai người hết bao nhiêu",
    "ăn nhóm 5 người giá bao nhiêu",
    "set menu giá bao nhiêu",
    "combo ăn uống bao nhiêu",
    "giá cả ăn uống ở Hà Nội thế nào",
    "ăn uống Đà Nẵng tốn bao nhiêu",
    "quán ăn cao cấp giá thế nào",
    "nhà hàng giá bao nhiêu",
    "quán ăn bình dân giá bao nhiêu",
    "bao nhiêu tiền vậy bạn",
    "giá nhiêu vậy",
    "giá cả ra sao",
    "hỏi giá quán phở",
    "check giá quán này",
    "price bao nhiêu",
    "how much",
    "giá menu quán này",
    "tầm bao nhiêu tiền",
    "giá tiền ăn sáng ở đây",
    "ăn trưa hết bao nhiêu",
    "ăn tối ở đây giá sao",
    "giá đồ uống ở quán",
    "một ly cà phê giá bao nhiêu",
    "giá vé máy bay đi Đà Nẵng",
    "chi phí tour du lịch",
    "giá tour Phú Quốc bao nhiêu",
]

# danh_gia: cần thêm ~70 mẫu (80→150)
danh_gia_phase4 = [
    "quán này có ngon không",
    "quán phở này đánh giá sao",
    "mọi người review quán này thế nào",
    "quán ăn này có tốt không bạn",
    "ai đã thử quán này chưa",
    "quán bún bò này review sao",
    "quán cà phê này có hay không",
    "đánh giá quán ăn này đi",
    "cho mình xem review",
    "review quán phở Hà Nội",
    "đánh giá nhà hàng này",
    "quán này bao nhiêu sao",
    "quán này rating bao nhiêu",
    "điểm đánh giá quán",
    "feedback quán ăn này",
    "comment về quán này",
    "quán này người ta nói sao",
    "quán này có được khen không",
    "quán này có nổi tiếng không",
    "quán này có đáng thử không",
    "quán này có worth it không",
    "quán ăn này ổn không",
    "phản hồi về quán này",
    "nhận xét quán phở Thìn",
    "cảm nhận quán bún chả",
    "quán này có bị chê không",
    "khách hàng nói gì về quán này",
    "quán cà phê view đẹp đánh giá",
    "resort này review thế nào",
    "khách sạn này đánh giá sao",
    "homestay này có tốt không",
    "địa điểm du lịch này review sao",
    "quán ăn nào được đánh giá cao nhất",
    "top quán ăn được review tốt",
    "quán nào nhiều sao nhất",
    "quán phở nào review tốt nhất Hà Nội",
    "quán bún bò Huế nào được khen",
    "quán cà phê Đà Lạt đánh giá sao",
    "quán ăn Sài Gòn review tốt",
    "quán nào nhiều lượt đánh giá",
    "quán này có review trên Google không",
    "đánh giá trên TripAdvisor",
    "quán này foody đánh giá sao",
    "shopee food rating quán này",
    "grab food quán này bao nhiêu sao",
    "quán này khách có đông không",
    "quán ăn được yêu thích nhất",
    "món nào được khen nhiều nhất",
    "phở ở đây có ngon thật không",
    "bún bò Huế quán này có được không",
    "hải sản ở Nha Trang đánh giá sao",
    "quán ăn vặt review",
    "quán trà sữa nào được đánh giá cao",
    "quán chay review thế nào",
    "quán buffet này đánh giá sao",
    "quán lẩu nào review tốt",
    "quán ăn gia đình đánh giá",
    "quán ăn cho trẻ em review",
    "quán nào phục vụ tốt",
    "thái độ phục vụ quán này",
    "chất lượng đồ ăn quán này sao",
    "vệ sinh quán ăn thế nào",
    "không gian quán thế nào",
    "quán có view đẹp không",
    "quán này có wifi không",
    "quán có chỗ đậu xe không",
    "quán mở cửa mấy giờ",
    "quán đông không vậy",
    "quán có cần đặt bàn không",
    "quán này có giao hàng không",
]

# so_sanh: cần thêm ~80 mẫu (70→150)
so_sanh_phase4 = [
    "phở hay bún bò ngon hơn",
    "nên ăn phở hay bún chả",
    "cơm tấm hay bún thịt nướng",
    "bánh mì hay cơm tấm ngon hơn",
    "bún bò hay bún riêu ngon hơn",
    "lẩu hay nướng ngon hơn",
    "hải sản hay thịt bò ngon hơn",
    "quán A hay quán B ngon hơn",
    "phở Hà Nội hay phở Sài Gòn ngon hơn",
    "bún chả Hà Nội hay Sài Gòn",
    "ẩm thực miền Bắc hay miền Nam",
    "ẩm thực Huế hay Đà Nẵng",
    "so sánh phở bò và phở gà",
    "so sánh bún riêu và bún bò",
    "so sánh bánh cuốn và bánh xèo",
    "so sánh cơm tấm và xôi",
    "so sánh lẩu thái và lẩu chua",
    "so sánh quán phở Thìn và phở Bát Đàn",
    "so sánh Đà Lạt và Sapa",
    "so sánh Đà Nẵng và Quy Nhơn",
    "so sánh Phú Quốc và Côn Đảo",
    "so sánh Hà Nội và TP HCM",
    "so sánh Nha Trang và Phan Thiết",
    "so sánh Hội An và Huế",
    "nên đi Đà Lạt hay Nha Trang",
    "nên đi Phú Quốc hay Quy Nhơn",
    "nên đi Đà Nẵng hay Huế",
    "nên du lịch biển hay núi",
    "biển Nha Trang hay Phú Quốc đẹp hơn",
    "Sapa hay Hà Giang đẹp hơn",
    "Đà Lạt hay Bà Nà đẹp hơn",
    "so sánh du lịch biển và du lịch núi",
    "khách sạn A hay khách sạn B tốt hơn",
    "resort Phú Quốc hay Nha Trang",
    "homestay Đà Lạt hay Sapa",
    "chọn quán nào ngon hơn",
    "đi đâu vui hơn",
    "ở đâu đẹp hơn",
    "ăn gì ngon hơn",
    "cái nào rẻ hơn",
    "quán nào đắt hơn",
    "quán nào ngon hơn",
    "quán nào sạch hơn",
    "quán nào đông hơn",
    "quán nào review tốt hơn",
    "món nào ngon hơn",
    "món nào lạ hơn",
    "nên thử cái nào trước",
    "cái nào đáng thử hơn",
    "ăn cái nào hợp hơn",
    "so sánh 2 quán này",
    "so sánh hai món này giúp mình",
    "so sánh quán ăn và nhà hàng",
    "quán ăn bình dân hay nhà hàng cao cấp",
    "buffet hay alacarte",
    "gọi món hay ăn buffet",
    "ăn quán nhỏ hay nhà hàng lớn",
    "quán vỉa hè hay quán sang",
    "đồ ăn đường phố hay nhà hàng",
    "street food hay fine dining",
    "so sánh giá 2 quán",
    "quán nào giá tốt hơn",
    "quán nào phục vụ tốt hơn",
    "compare hai quán này",
    "quán nào mình nên chọn",
    "nên ăn ở đâu hơn",
    "tôi nên chọn quán nào",
    "gợi ý so sánh 2 địa điểm",
    "địa điểm nào đáng đi hơn",
    "nên đi đâu hơn",
    "du lịch đâu vui hơn",
    "du lịch đâu rẻ hơn",
    "chỗ nào đáng đi hơn",
    "nơi nào view đẹp hơn",
    "quán nào không gian đẹp hơn",
    "ăn Nhật hay ăn Hàn ngon hơn",
    "đồ Thái hay đồ Việt ngon hơn",
    "pizza hay pasta ngon hơn",
    "trà sữa hay cà phê",
    "quán trà sữa nào ngon nhất",
]

# ==============================================================================
# 3. AGGREGATE & APPEND VÀO FILE CSV (có dedup)
# ==============================================================================

all_new = []
for text in chao_hoi_phase4: all_new.append((text, "chao_hoi"))
for text in cam_on_phase4: all_new.append((text, "cam_on"))
for text in tam_biet_phase4: all_new.append((text, "tam_biet"))
for text in hoi_thong_tin_phase4: all_new.append((text, "hoi_thong_tin"))
for text in hoi_gia_phase4: all_new.append((text, "hoi_gia"))
for text in danh_gia_phase4: all_new.append((text, "danh_gia"))
for text in so_sanh_phase4: all_new.append((text, "so_sanh"))

print(f"=== THỐNG KÊ DỮ LIỆU PHASE 4 ===")
print(f"  chao_hoi: +{len(chao_hoi_phase4)} mẫu mới")
print(f"  cam_on: +{len(cam_on_phase4)} mẫu mới")
print(f"  tam_biet: +{len(tam_biet_phase4)} mẫu mới")
print(f"  hoi_thong_tin: +{len(hoi_thong_tin_phase4)} mẫu mới")
print(f"  hoi_gia: +{len(hoi_gia_phase4)} mẫu mới")
print(f"  danh_gia: +{len(danh_gia_phase4)} mẫu mới")
print(f"  so_sanh: +{len(so_sanh_phase4)} mẫu mới")
print(f"  TỔNG: {len(all_new)} mẫu mới")

# Đọc dữ liệu hiện tại để chống trùng lặp (dedup)
existing_texts = set()
if os.path.exists(DATASET_PATH):
    with open(DATASET_PATH, 'r', encoding='utf-8-sig') as f:
        reader = csv.reader(f)
        next(reader, None)  # bỏ qua header
        for row in reader:
            if row:
                existing_texts.add(row[0].strip())

# Lọc ra chỉ những câu CHƯA có trong dataset
new_only = [(text, intent) for text, intent in all_new if text.strip() not in existing_texts]
skipped = len(all_new) - len(new_only)

# Append vào CSV
with open(DATASET_PATH, 'a', encoding='utf-8-sig', newline='') as f:
    writer = csv.writer(f)
    for text, intent in new_only:
        writer.writerow([text, intent])

print(f"\nĐã append {len(new_only)} mẫu mới vào {DATASET_PATH} (bỏ qua {skipped} mẫu trùng lặp)")

# Đọc lại để kiểm tra phân bố
with open(DATASET_PATH, 'r', encoding='utf-8-sig') as f:
    reader = csv.reader(f)
    next(reader)  # bỏ qua header
    counts = collections.Counter(row[-1] for row in reader if row)

print(f"\n=== PHÂN BỐ SAU KHI CẬP NHẬT ===")
total = sum(counts.values())
for intent, count in counts.most_common():
    print(f"  {intent}: {count} mẫu ({count*100//total}%)")
print(f"  TỔNG: {total} mẫu")
